# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: cargo 
    directory: "/" 
    schedule:
      interval: daily
      time: "03:00"
      timezone: Asia/Shanghai
    ignore:
    - dependency-name: creep
      versions:
      - 0.3.x
    - dependency-name: rand
      versions:
      - 0.8.x

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Asia/Shanghai

  - package-ecosystem: "npm"
    directory: "/tests/e2e"
    schedule:
      interval: weekly
      day: wednesday
      timezone: Asia/Shanghai
  
  - package-ecosystem: "npm"
    directory: "/builtin-contract/crosschain"
    schedule:
      interval: weekly
      day: wednesday
      timezone: Asia/Shanghai

  - package-ecosystem: "npm"
    directory: "/builtin-contract/metadata"
    schedule:
      interval: weekly
      day: wednesday
      timezone: Asia/Shanghai
