underlying:
- any: ['core/consensus/*', 'core/mempool/*', 'core/executor/*', 'core/network/*', 'core/storage']

API:
- core/api/*

interoperation:
- core/interoperation/*

crosschain:
- any: ['core/cross-client/*', 'core/tx-assembler/*']

devtools:
- devtools/*

documents:
- any: ['docs/*', README.md, CHANGELOG.md]

e2e:
- tests/e2e/*

contract:
- builtin-contract/*

protocol:
- protocol/*

toolchain: 
- rust-toolchain

ci: 
- any: ['.github/actions/*', '.github/workflows/*']

apm: 
- any: ['common/apm/*', 'common/apm-derive/*', 'common/memory-tracker/*']

config:
- any: ['common/config-parser/*']
