version: '3.8'

services:
  axon:
    container_name: axon
    build: .
    restart: always
    privileged: true
    ports:
      - 8000:8000
    volumes:
      - ./devtools:/app/devtools
    networks:
      - axon-net
    command: ./axon -c=/app/devtools/chain/config.toml -g=/app/devtools/chain/genesis_single_node.json


networks:
  axon-net:
