version: '3.8'

services:
  axon:
    container_name: axon
    build: .
    restart: always
    privileged: true
    ports:
      - 8000:8000
    volumes:
      - ./devtools:/app/devtools
    networks:
      - axon-net
    command: ./axon run -c=/app/devtools/chain/config.toml -s=/app/devtools/chain/specs/single_node/chain-spec.toml


networks:
  axon-net:
