name: axon_genesis_generator
version: "0.1"
about: a tool to generate genesis for axon
author: axon Dev <axon@nervos.org>

args:
  - private_key:
      help: private key to generate transaction
      short: p
      long: private_key
      # just for testing
      default_value: "0x37aa0f893d05914a4def0460c0a984d3611546cfb26924d7a7ca6e0db9950a2d"

  - chain_id:
      help: chain id
      short: c
      long: chain_id
      default_value: "2022"

  - config_path:
      help: config file path to generate metadata
      short: f
      long: config_path
      takes_value: true
      default_value: "./../chain"
