[package]
name = "core-cross-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { path = "../../protocol", package = "axon-protocol"}
common-config-parser = { path = "../../common/config-parser" }
common-crypto = { path = "../../common/crypto"}
core-executor = { path = "../../core/executor" }


cita_trie = "3.0"
ckb-jsonrpc-types = "0.101"
futures = "0.3"
jsonrpc-core = "18.0"
tokio-util = { version = "0.6", features = ["codec"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ckb-types = "0.101.3"
reqwest = { version = "0.11.1", features = ["json"] }
log = "0.4"
