[package]
name = "core-executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cita_trie = "3.0"
crossbeam-channel = "0.5"
dashmap = "5.0"
evm = "0.33.0"
futures = "0.3"
hasher = "0.1"
lazy_static = "1.4"
log = "0.4"
rand = { version = "0.8", features = ["small_rng"] }
rocksdb = "0.17"
parking_lot = "0.11"

protocol = { path = "../../protocol", package = "axon-protocol"}
common-apm = { path = "../../common/apm" }
common-merkle = { path = "../../common/merkle" }

[dev-dependencies]
hex = "0.4"
