[package]
edition = "2021"
name = "core-executor"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
az = "1.2"
bn = { package = "substrate-bn", version = "0.6" }
cita_trie = "3.0"
crossbeam-channel = "0.5"
evm = "0.35"
futures = "0.3"
hasher = "0.1"
lazy_static = "1.4"
log = "0.4"
parking_lot = "0.12"
rand = { version = "0.8", features = ["small_rng"] }
ripemd = "0.1"
rlp = "0.5"
rocksdb = {version = "0.18", package = "ckb-rocksdb"}
rug = "1.16"
sha2 = "0.10"

common-apm = { path = "../../common/apm" }
common-config-parser = { path = "../../common/config-parser" }
common-crypto = { path = "../../common/crypto" }
common-merkle = { path = "../../common/merkle" }
core-interoperation = { path = "../interoperation" }
protocol = { path = "../../protocol", package = "axon-protocol" }

[dev-dependencies]
common-crypto = { path = "../../common/crypto" }
core-storage = { path = "../storage" }

criterion = "0.3"
ethabi = "17.1"
ethabi-contract = { git = "https://github.com/rust-ethereum/ethabi.git", rev = "7edf185" }
ethabi-derive = { git = "https://github.com/rust-ethereum/ethabi.git", rev = "7edf185" }
getrandom = "0.2"
rlp = "0.5"
tempfile = "3.3"

[[bench]]
harness = false
name = "bench_transfer"
