[package]
name = "core-executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
futures = "0.3"
ethereum = "0.10.0"
evm = "0.33.0"
protocol = { path = "../../protocol", package = "axon-protocol"}

[dev-dependencies]
hex = "*"
