[package]
name = "axon-protocol"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.5"
async-trait = "0.1"
bincode = "1.3"
bytes = { version = "1.1", features = ["serde"] }

common-crypto = { path = "../common/crypto" }
creep = "0.2"
derive_more = "0.99"
ethereum = "0.11"
ethereum-types = "0.12"
evm = { version = "0.33", features = ["with-codec", "with-serde"] }
faster-hex = "0.6"
hasher = { version = "0.1", features = ["hash-keccak"] }
hex-simd = "0.5"
lazy_static = "1.4"
ophelia = "0.3"
ophelia-secp256k1 = "0.3"
overlord = "0.3"
rlp = "0.5"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.17", features = ["full"] }

[dev-dependencies]
getrandom = "0.2"
hex = "0.4"
rand = "0.7"
serde_json = "1.0"
toml = "0.5"
