[package]
name = "core-mempool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cita_trie = "3.0"
crossbeam-queue = "0.3"
futures = { version = "0.3", features = [ "async-await" ] }
hex = "0.4"
log = "0.4"
rand = "0.7"
rayon = "1.5"
rlp = "0.5"
rlp-derive = "0.1"
parking_lot = "0.11"

protocol = { path = "../../protocol", package = "axon-protocol"}
common-apm = { path = "../../common/apm" }
common-crypto = { path = "../../common/crypto" }
core-executor = { path = "../../core/executor" }

[dev-dependencies]
dashmap = "5.0"
parking_lot = "0.11"
