[package]
name = "core-storage"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.4"
futures = "0.3"
lazy_static = "1.4"
log = "0.4"
parking_lot = "0.12"
rocksdb = { version = "0.16", package = "ckb-rocksdb" }

common-apm = { path = "../../common/apm" }
protocol = { path = "../../protocol", package = "axon-protocol" }

[dev-dependencies]
num-traits = "0.2"
rand = "0.7"
