[package]
name = "core-network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { path = "../../protocol", package = "axon-protocol"}

tentacle = { version = "=0.4.0-alpha.2", features = ["parking_lot"] }
rlp = "0.5"
snap = "1.0"
bytes = "1.1"
log = "0.4"
rand = "0.7"
bloom-filters = "0.1"
prost = "0.9"
futures = "0.3"
derive_more = "0.99"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
async-trait = "0.1"
parking_lot = "0.11"
hex = "0.4.3"
tokio-util = { version = "0.6.9", features = ["codec"] }
ipnetwork = "0.18"
faketime = "0.2.0"

[dev-dependencies]
env_logger = "0.9"
