# crypto
net_privkey = "0x65a7dcfc524df2e6b2f8ff0051ee5077bf3a995962cbfcdd8de53224aa3026df"
bls_privkey = "0x383fcff8683b8115e31613949be24254b4204ffbe43c227408a76334a2e3fb32"

# db config
data_path = "./devtools/chain/data2"

[rpc]
http_listening_address = "0.0.0.0:8000"
ws_listening_address = "0.0.0.0:8010"
maxconn = 25000
max_payload_size = 10485760
client_version = "0.1.0"

[web3]
max_gas_cap = 50_000_000
log_filter_max_block_range = 25000

[network]
listening_address = "/ip4/0.0.0.0/tcp/8001"
rpc_timeout = 10

[synchronization]
sync_txs_chunk_size = 5000

[[network.bootstraps]]
multi_address = "/dns4/axon1/tcp/8001/p2p/QmY5oSuqWmbTV6k7fmQgWuXU4ui2avDEhnobr2KHBHkkWA"

[[network.bootstraps]]
multi_address = "/dns4/axon2/tcp/8001/p2p/QmUu16gPSw4QjR6D6rcZ48jFzEudoHKV52r2AfTRM1MNN7"

[[network.bootstraps]]
multi_address = "/dns4/axon3/tcp/8001/p2p/QmWZvKC6Cy2Uu8qQ1asCXyn9TA8cD1NXpYGtfPitXYhCsa"

[[network.bootstraps]]
multi_address = "/dns4/axon4/tcp/8001/p2p/QmUG47QnBXC9tvESroV2NngTE6rbHsM1167GxPJexxPYyM"

[mempool]
timeout_gap = 20
pool_size = 20000000
broadcast_txs_size = 200
broadcast_txs_interval = 200

[executor]
triedb_cache_size = 500

[logger]
filter = "info"
log_to_console = true
console_show_file_and_line = false
log_path = "logs/"
log_to_file = true
file_size_limit = 1073741824 # 1 GiB
metrics = true
# you can specify log level for modules with config below
# modules_level = { "overlord::state::process" = "debug" }

[rocksdb]
max_open_files = 64
cache_size = 200
# Provide an options file to tune RocksDB for your workload and your system configuration.
# More details can be found in [the official tuning guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide).
options_file = "default.db-options"
