# crypto
net_privkey = "0x37aa0f893d05914a4def0460c0a984d3611546cfb26924d7a7ca6e0db9950a2d"
bls_privkey = "0x4179b05f5ad5bdd46ca98a9e8b435b00a504562dfe02687895edf747ddf5de18"

# db config
data_path = "./devtools/chain/data1"

[rpc]
http_listening_address = "0.0.0.0:8000"
ws_listening_address = "0.0.0.0:8010"
maxconn = 25000
max_payload_size = 10485760
client_version = "0.1.0"

[web3]
max_gas_cap = 50_000_000
log_filter_max_block_range = 25000

[network]
listening_address = "/ip4/0.0.0.0/tcp/8001"
rpc_timeout = 10

[synchronization]
sync_txs_chunk_size = 5000

[[network.bootstraps]]
multi_address = "/dns4/axon1/tcp/8001/p2p/QmNk6bBwkLPuqnsrtxpp819XLZY3ymgjs3p1nKtxBVgqxj"

[[network.bootstraps]]
multi_address = "/dns4/axon2/tcp/8001/p2p/QmaHBJqULbLGDn7Td196goNebH6XMTMMu2sKNNP2DiX9S2"

[[network.bootstraps]]
multi_address = "/dns4/axon3/tcp/8001/p2p/QmQLufVVmBuHKoYhdDCqUFYVtLYs1quryoaA1mkQYQdWkn"

[[network.bootstraps]]
multi_address = "/dns4/axon4/tcp/8001/p2p/QmXoSkz4zkHHiFZqmDZQ4gFYtJ72uqtp4m6FX373X4VkRq"

[mempool]
timeout_gap = 20
pool_size = 20000000
broadcast_txs_size = 200
broadcast_txs_interval = 200

[executor]
triedb_cache_size = 500

[logger]
filter = "info"
log_to_console = true
console_show_file_and_line = false
log_path = "logs/"
log_to_file = true
file_size_limit = 1073741824 # 1 GiB
metrics = true
# you can specify log level for modules with config below
# modules_level = { "overlord::state::process" = "debug" }

[rocksdb]
max_open_files = 64
cache_size = 200
# Provide an options file to tune RocksDB for your workload and your system configuration.
# More details can be found in [the official tuning guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide).
options_file = "default.db-options"
