---
- hosts: "{{ hostname }}"
  remote_user: ec2-user
  become: yes
  become_method: sudo
  vars_files:
    - config.yml
  tasks:
    - name: Install git && docker
      shell: sudo yum install git docker -y && sudo service docker start
      become: yes
      become_method: sudo
      tags:
        - build
    - name: Pull code
      git:
        repo: "https://github.com/axonweb3/axon.git"
        dest: "axon"
        version: "main"
        force: yes
      become: yes
      become_method: sudo
      tags:
        - build

    - name: docker build
      shell: cd axon && docker build -t axonweb3/axon:{{ image_tag }} .
      become: yes
      become_method: sudo
      tags:
        - build

    - name: docker login and push image
      shell: docker login -u {{ docker_user }} -p {{ docker_password }} && docker push axonweb3/axon:{{ image_tag }}
      become: yes
      become_method: sudo
      tags:
        - build
