# crypto
privkey = "0x37aa0f893d05914a4def0460c0a984d3611546cfb26924d7a7ca6e0db9950a2d"

# db config
data_path = "./devtools/chain/data"

crosschain_contract_address = "0xb9dc8bde1db42410d304b5e78c2ff843134e15e0"
wckb_contract_address = "0xa13763691970d9373d4fab7cc323d7ba06fa9986"

[[accounts]]
address = "0xa0ee7a142d267c1f36714e4a8f75612f20a79720"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
address = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
balance = "04ee2d6d415b85acef8100000000"

[rpc]
http_listening_address = "0.0.0.0:8000"
ws_listening_address = "0.0.0.0:8010"
maxconn = 25000
max_payload_size = 10485760
client_version = "0.1.0"

[network]
listening_address = "/ip4/0.0.0.0/tcp/8001"
rpc_timeout = 10

[consensus]
overlord_gap = 5
sync_txs_chunk_size = 5000

[[network.bootstraps]]
multi_address = "/ip4/127.0.0.1/tcp/8001/p2p/QmNk6bBwkLPuqnsrtxpp819XLZY3ymgjs3p1nKtxBVgqxj"

[mempool]
timeout_gap = 20
pool_size = 20000000
broadcast_txs_size = 200
broadcast_txs_interval = 200

[executor]
light = false
triedb_cache_size = 2000

[logger]
filter = "info"
log_to_console = true
console_show_file_and_line = false
log_path = "logs/"
log_to_file = true
file_size_limit = 1073741824 # 1 GiB
metrics = true
# you can specify log level for modules with config below
# modules_level = { "overlord::state::process" = "debug", core_consensus = "error" }

[rocksdb]
max_open_files = 64
cache_size = 134217728
# Provide an options file to tune RocksDB for your workload and your system configuration.
# More details can be found in [the official tuning guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide).
options_file = "default.db-options"

[jaeger]
service_name = "axon"
tracing_address = "127.0.0.1:6831"
tracing_batch_size = 50

[prometheus]
listening_address = "0.0.0.0:8100"
