# crypto
# file paths to private keys.
# net_privkey is used for network, bls_privkey is use for sign consensus messages
# DO NOT USE this private key in any production environment!
net_privkey_file = "net.key"
bls_privkey_file = "bls.key"

# db config
data_path = "./devtools/chain/data"

[rpc]
http_listening_address = "0.0.0.0:8000"
ws_listening_address = "0.0.0.0:8010"
maxconn = 25000
max_payload_size = 10_485_760
client_version = "0.1.0"

[web3]
max_gas_cap = 50_000_000
log_filter_max_block_range = 25000

[network]
listening_address = "/ip4/0.0.0.0/tcp/8001"
rpc_timeout = 10

[synchronization]
sync_txs_chunk_size = 5000

[[network.bootstraps]]
multi_address = "/ip4/127.0.0.1/tcp/8001/p2p/QmNk6bBwkLPuqnsrtxpp819XLZY3ymgjs3p1nKtxBVgqxj"

[mempool]
timeout_gap = 20
pool_size = 20000000
broadcast_txs_size = 200
broadcast_txs_interval = 200

[executor]
triedb_cache_size = 200

[logger]
filter = "info"
log_to_console = true
console_show_file_and_line = false
log_path = "logs/"
log_to_file = true
file_size_limit = 1073741824       # 1 GiB
metrics = true
# you can specify log level for modules with config below
# modules_level = { "overlord::state::process" = "debug", core_consensus = "error" }

[rocksdb]
max_open_files = 64
cache_size = 100
# Provide an options file to tune RocksDB for your workload and your system configuration.
# More details can be found in [the official tuning guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide).
options_file = "default.db-options"

[jaeger]
service_name = "axon"
tracing_address = "127.0.0.1:6831"
tracing_batch_size = 50

[prometheus]
listening_address = "0.0.0.0:8100"
