# crypto
privkey = "0x3f1db3ea361e8707ce4d4e7a2af8e51d789fcd9e045fca472657fca80f019164"

# db config
data_path = "./devtools/chain/data/node_4"

[graphql]
listening_address = "127.0.0.1:8000"
graphql_uri = "/graphql"
graphiql_uri = "/graphiql"
workers = 0 # if 0, uses number of available logical cpu as threads count.
maxconn = 25000
max_payload_size = 1048576
# enable_dump_profile = false
# [graphql.tls]
# private_key_file_path = "key.pem"
# certificate_chain_file_path = "cert.pem"


[network]
listening_address = "/ip4/127.0.0.1/tcp/10004"
rpc_timeout = 10

[consensus]
overlord_gap = 5
sync_txs_chunk_size = 5000

[[network.bootstraps]]
multi_address = "/ip4/127.0.0.1/tcp/10004/p2p/QmVBtiL1x7HVBduSnMGu3TzamZNKabQk2hMZwg4ephWnQ9"

[[network.bootstraps]]
multi_address = "/ip4/127.0.0.1/tcp/10003/p2p/QmWbtw4PrPheTFe1qsyykECroJMYVe75VKz2CnvyqoRgNt"

[[network.bootstraps]]
multi_address = "/ip4/127.0.0.1/tcp/10002/p2p/QmSHdghJyce54sqmuBWJNUUwxYu2HPmED4NDJHFTuVs7ng"

[[network.bootstraps]]
multi_address = "/ip4/127.0.0.1/tcp/10001/p2p/QmQTuFXwu5tD9EGAXnTFWirQivrebxX7wDEwZPz76GB3zQ"

[mempool]
timeout_gap = 20
pool_size = 20000
broadcast_txs_size = 200
broadcast_txs_interval = 200

[executor]
light = false
triedb_cache_size = 2000

[logger]
filter = "info"
log_to_console = true
console_show_file_and_line = false
log_path = "logs/node_4/"
log_to_file = true
file_size_limit = 1073741824 # 1 GiB
metrics = true
# you can specify log level for modules with config below
# modules_level = { "overlord::state::process" = "debug", core_consensus = "error" }

[rocksdb]
max_open_files = 64

# [apm]
# service_name = "muta"
# tracing_address = "127.0.0.1:6831"
# tracing_batch_size = 50
