# crypto
net_privkey = "0x4d9ff772f801b4d927260ca3b3432b6add343daabd98570033cbb16e95918498"
bls_privkey = "0x51ce21643b911347c5d5c85c323d9d5421810dc89f46b688720b2715f5e8e936"

# db config
data_path = "./devtools/chain/data/node_3"

[rpc]
http_listening_address = "127.0.0.1:8003"
ws_listening_address = "127.0.0.1:8013"
maxconn = 25000
max_payload_size = 1048576

[web3]
max_gas_cap = 50_000_000
log_filter_max_block_range = 25000

[network]
listening_address = "/ip4/127.0.0.1/tcp/10003"
rpc_timeout = 10

[synchronization]
sync_txs_chunk_size = 5000

[[network.bootstraps]]
multi_address = "/ip4/127.0.0.1/tcp/10004/p2p/QmUG47QnBXC9tvESroV2NngTE6rbHsM1167GxPJexxPYyM"

[[network.bootstraps]]
multi_address = "/ip4/127.0.0.1/tcp/10003/p2p/QmWZvKC6Cy2Uu8qQ1asCXyn9TA8cD1NXpYGtfPitXYhCsa"

[[network.bootstraps]]
multi_address = "/ip4/127.0.0.1/tcp/10002/p2p/QmUu16gPSw4QjR6D6rcZ48jFzEudoHKV52r2AfTRM1MNN7"

[[network.bootstraps]]
multi_address = "/ip4/127.0.0.1/tcp/10001/p2p/QmY5oSuqWmbTV6k7fmQgWuXU4ui2avDEhnobr2KHBHkkWA"

[mempool]
timeout_gap = 20
pool_size = 20000
broadcast_txs_size = 200
broadcast_txs_interval = 200

[executor]
triedb_cache_size = 500

[logger]
filter = "info"
log_to_console = true
console_show_file_and_line = false
log_path = "logs/node_3"
log_to_file = true
file_size_limit = 1073741824 # 1 GiB
metrics = true
# you can specify log level for modules with config below
# modules_level = { "overlord::state::process" = "debug", core_consensus = "error" }

[rocksdb]
max_open_files = 64
cache_size = 200
# Provide an options file to tune RocksDB for your workload and your system configuration.
# More details can be found in [the official tuning guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide).
options_file = "default.db-options"
