name: Chaos CI
concurrency:
  group: Chaos CI-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:

jobs:
  prologue:
    name: prologue
    runs-on: ubuntu-20.04
    outputs:
      job_skip: ${{ steps.prologue.outputs.job_skip }}
    steps:
    - uses: actions/checkout@v3
    - name: prologue
      id: prologue
      uses: ./.github/actions/ci_prologue
      with:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        PR_COMMONS_BODY: "${{ github.event.pull_request.body }}"
        GITHUB_WORKFLOW: ${{ github.workflow }}
  build:
    needs: prologue
    runs-on: self-hosted
    environment: chaos
    if: needs.prologue.outputs.job_skip == 'run'
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build Axon
        run: |
          cd /home/ckb/axon-devops/axon-image/
          ansible-playbook build.yml --tags build -e axon_branch=${{ github.head_ref }} -e pr_number=${{ github.event.pull_request.number }}

      - name: Run chaos
        run: |
          cd /home/ckb/axon-devops/axon-chaos/axon-chaos-integration
          yarn install
          node index.js ${{ secrets.CHAOS_URL }}
