name: Chaos CI
on:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build Axon
        run: |
          cd /home/ckb/axon-devops/axon-image/
          ansible-playbook build.yml --tags build -e axon_branch=${{ github.head_ref }} -e pr_number=${{ github.event.pull_request.number }}

      - name: Run chaos
        run: |
          kubectl delete -f /home/ckb/axon-devops/axon-chaos/axon-chaso.yaml
          kubectl delete -f /home/ckb/axon-devops/k8s-deploy/k8s/benchmark/axon-benchmark.yaml
          kubectl delete -f /home/ckb/axon-devops/k8s-deploy/k8s/axon
          kubectl apply -f /home/ckb/axon-devops/k8s-deploy/k8s/axon
          kubectl apply -f /home/ckb/axon-devops/axon-chaos/axon-chaso.yaml
          kubectl apply -f /home/ckb/axon-devops/k8s-deploy/k8s/benchmark/axon-benchmark.yaml
