name: Chaos CI
on:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    environment: chaos
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build Axon
        run: |
          cd /home/ckb/axon-devops/axon-image/
          ansible-playbook build.yml --tags build -e axon_branch=${{ github.head_ref }} -e pr_number=${{ github.event.pull_request.number }}

      - name: Run chaos
        run: |
          cd /home/ckb/axon-devops/axon-chaos/axon-chaos-integration
          yarn install
          node index.js ${{ secrets.CHAOS_URL }}
