name: Automated PR to DEVOPS
on:
  push:
    branches:
      - main
    paths:
    - 'devtools/chain/default.db-options'
    - 'devtools/chain/specs/multi_nodes'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 2
      - name: Git checkout devops
        uses: actions/checkout@v3
        with:
          repository: axonweb3/axon-devops
          path: ${{ github.workspace}}/axon-devops
      - name: apply config toml config_toml.patch
        run: |
          # copy default.db-options & specs/multi_nodes to axon-devops always
          cp ${{ github.workspace}}/devtools/chain/default.db-options ${{ github.workspace}}/axon-devops/deploy/templates
          cp ${{ github.workspace}}/devtools/chain/default.db-options ${{ github.workspace}}/axon-devops/docker-deploy/devtools/chain
          cp ${{ github.workspace}}/devtools/chain/default.db-options ${{ github.workspace}}/axon-devops/k8s-deploy/k8s/axon/axon-config
          cp -r ${{ github.workspace}}/devtools/chain/nodes/specs/multi_nodes ${{ github.workspace}}/axon-devops/deploy/templates/specs
          cp -r ${{ github.workspace}}/devtools/chain/nodes/specs/multi_nodes ${{ github.workspace}}/axon-devops/docker-deploy/devtools/chain/specs
          cp -r ${{ github.workspace}}/devtools/chain/nodes/specs/multi_nodes ${{ github.workspace}}/axon-devops/k8s-deploy/k8s/axon/axon-config/specs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
           token: ${{ secrets.TOKEN }}
           path: ${{ github.workspace}}/axon-devops
           signoff: false
           commit-message: "feat: automated pr to change config files"
           branch: bot-${{ github.repository }}
           title: "feat: automated pr to change config files"
           body: "Automated pr to changes config files by GitHub action"
      - name: Send some mail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }},please have a check:https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: liya@cryptape.com
          from: me
