name: Coverage Test
concurrency:
  group: Coverage Test-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  prologue:
    name: prologue
    if: |
      (github.event_name == 'issue_comment' &&
       contains(github.event.review.body, '/run-ci')
       ) ||
       (github.event_name == 'pull_request' && github.event.action == 'synchronize') ||
       github.event_name == 'push'
    runs-on: ubuntu-20.04
    outputs:
      job_skip: ${{ steps.prologue.outputs.job_skip }}
    steps:
      - uses: actions/checkout@v3
      - name: prologue
        id: prologue
        uses: ./.github/actions/ci_prologue
        with:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          PR_COMMONS_BODY: "${{ github.event.pull_request.body }}"
          GITHUB_WORKFLOW: ${{ github.workflow }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
  Coverage:
    needs: prologue
    if: needs.prologue.outputs.job_skip == 'run'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lyricwulf/abc@v1
        with:
          linux: m4

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-01-21
          override: true

      - name: run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: "--avoid-cfg-tarpaulin -p core-executor -p core-mempool -p core-storage -p core-metadata -- --test-threads 1"

      - name: upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml
