name: PR Lint
concurrency:
  group: Conventional PR-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  WIP:
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Conventional:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Namchee/conventional-pr@v0.12.1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # to override config-conventional rules, specify a relative path to your rules module, actions/checkout is required for this setting!
          # commitlintRulesPath: "./commitlint.rules.js" # default: undefined
          close: false
          issue: false
          message: 'The title of this PR does not conform the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). Please fix it, thx.'

          # if the PR contains a single commit, fail if the commit message and the PR title do not match
          access_token: ${{ secrets.GITHUB_TOKEN }}

  Label:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels based on PR title
        uses: TDAK1509/set-label-based-on-pr-title@v1
        with:
          words: feat;perf;refactor;fix;chore;docs;style;ci
          labels: feature;enhancement;refactor;bugfix;chore;document;style;skip_changelog
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  # Triage:
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/labeler@v4
  #       with:
  #         repo-token: "${{ secrets.GITHUB_TOKEN }}"
  #         configuration-path: '.github/config/_labeler.yml'
  #         sync-labels: true
