name: Regression test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  invoke-fmt-test:
    if: github.repository_owner == 'axonweb3'
    runs-on: ubuntu-latest
    steps:
      - name: Invoke fmt test
        id: invoke-fmt-test
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Code Format
          token: ${{ secrets.GITHUB_TOKEN }}

  invoke-v3-core-test:
    if: github.repository_owner == 'axonweb3'
    runs-on: ubuntu-latest
    steps:
      - name: Invoke v3 core test
        id: invoke-v3-core-test
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow:  v3 Core Tests
          wait-for-completion-timeout: 2h
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "dispatch": "regression" }'

  invoke-web3-compatible-test:
    if: github.repository_owner == 'axonweb3'
    runs-on: ubuntu-latest
    steps:
      - name: Invoke web3 compatible test
        id: invoke-web3-compatible-test
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow:  Web3 Compatible Tests
          wait-for-completion-timeout: 2h
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "dispatch": "regression" }'

  invoke-openzeppelin-test-1-5-and-12-15-test:
    if: github.repository_owner == 'axonweb3'
    runs-on: ubuntu-latest
    steps:
      - name: Invoke OCT 1-5 And 12-15 test
        id: invoke-openzeppelin-test-1-5-and-12-15-test
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow:  OCT 1-5 And 12-15
          wait-for-completion-timeout: 2h
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "dispatch": "regression" }'

  invoke-OCT-6-10-test:
    if: github.repository_owner == 'axonweb3'
    runs-on: ubuntu-latest
    steps:
      - name: Invoke OCT 1-5 And 12-15 test
        id: invoke-OCT-6-10-test
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow:  OCT 6-10
          wait-for-completion-timeout: 2h
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "dispatch": "regression" }'

  invoke-OCT-11-test:
    if: github.repository_owner == 'axonweb3'
    runs-on: ubuntu-latest
    steps:
      - name: Invoke OCT 11 test
        id: invoke-OCT-11-test
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow:  OCT 11
          wait-for-completion-timeout: 2h
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "dispatch": "regression" }'

  invoke-OCT-16-19-test:
    if: github.repository_owner == 'axonweb3'
    runs-on: ubuntu-latest
    steps:
      - name: Invoke OCT 16-19 test
        id: invoke-OCT-16-19-test
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow:  OCT 16-19
          wait-for-completion-timeout: 2h
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "dispatch": "regression" }'

  output-result:
    runs-on: ubuntu-latest
    needs: [invoke-fmt-test,invoke-v3-core-test,invoke-web3-compatible-test,invoke-openzeppelin-test-1-5-and-12-15-test,invoke-OCT-6-10-test,invoke-OCT-11-test,invoke-OCT-16-19-test]
    if: github.repository_owner == 'axonweb3' && always()
    steps:
    - name: send message
      uses: nobrayner/discord-webhook@v1
      with:
        github-token: ${{ secrets.github_token }}
        discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
