name: Release
on:
  push:
    tags:
      - v*.*.*
    # branches:
    #   - "main"
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      major: ${{ steps.version.outputs.major }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: version
        id: version
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          version=${tag#v}
          major=${version%%.*}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "major=${major}" >> $GITHUB_OUTPUT
      - name: Get release
        id: release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token }}
          tag_name: ${{ steps.version.outputs.tag }}

  package:    
    runs-on: ${{ matrix.job.os }}
    needs:
      - version
    strategy:
      matrix:
        job:
          - os: macos-12
            target: x86_64-apple-darwin
            use-cross: false
            REL_PKG: x86_64-apple-darwin.zip
          # - os: macos-latest
          #   target: aarch64-apple-darwin
          #   use-cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: false
            REL_PKG: x86_64-unknown-linux-gnu.tar.gz
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          profile: minimal
          override: true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add rust target
        run: rustup target add ${{ matrix.job.target }}
      - run: |
          cargo build --release --target ${{ matrix.job.target }}
          rm -rf releases
          mkdir releases
          REL_PKG=${{ matrix.job.REL_PKG}}
          PKG_NAME="axon_${{ needs.version.outputs.tag }}_${REL_PKG%%.*}"
          mkdir "releases/$PKG_NAME"
          cp "target/${{ matrix.job.target }}/release/axon" "releases/$PKG_NAME"
          cp "devtools/chain/config.toml" "releases/$PKG_NAME"
          cp "devtools/chain/default.db-options" "releases/$PKG_NAME"
          cp "devtools/chain/genesis_single_node.json" "releases/$PKG_NAME"
          cp "devtools/chain/nodes/genesis_multi_nodes.json" "releases/$PKG_NAME"
          cp README.md "releases/$PKG_NAME"
          cp -R docs "releases/$PKG_NAME"
          cp core/api/README.md "releases/$PKG_NAME/docs/rpc.md"
          pushd releases
          if [ "${REL_PKG#*.}" = "tar.gz" ]; then
            tar -czf $PKG_NAME.tar.gz $PKG_NAME
          else
            zip -r $PKG_NAME.zip $PKG_NAME
          fi
          popd
          mv ${{ github.workspace }}/releases/axon_${{ needs.version.outputs.tag }}_${{ matrix.job.REL_PKG}} ${{ github.workspace }}
      - name: upload-zip-file
        uses: actions/upload-artifact@v2
        with:
          name: axon_${{ needs.version.outputs.tag }}_${{ matrix.job.REL_PKG }}
          path: axon_${{ needs.version.outputs.tag }}_${{ matrix.job.REL_PKG }}  
  Upload-release-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - REL_PKG: x86_64-unknown-linux-gnu.tar.gz
          - REL_PKG: x86_64-apple-darwin.zip
    needs:
      - version
      - package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare - Download tar
        uses: actions/download-artifact@v3
        with:
          name: axon_${{ needs.version.outputs.tag }}_${{ matrix.REL_PKG }}  
      - name: Upload tar assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.version.outputs.upload_url }}
          asset_name: axon_${{ needs.version.outputs.tag }}_${{ matrix.REL_PKG }}
          asset_path: ${{ github.workspace }}/axon_${{ needs.version.outputs.tag }}_${{ matrix.REL_PKG }}
          asset_content_type: application/octet-stream
  force-push:
    runs-on: ubuntu-latest
    needs:
      - version
      - Upload-release-files
    steps:
      - uses: actions/checkout@v3
      - name: force update major tag
        run: |
          git tag v${{ needs.version.outputs.major }} ${{ needs.version.outputs.tag }} -f
          git push origin refs/tags/v${{ needs.version.outputs.major }} -f


  trigger-somking-test:
    runs-on: ubuntu-latest
    needs:
      - version
      - package
    steps:
      - uses: actions/checkout@v3
      - name: Generate axon-bot token
        id: generate_axon_bot_token
        uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.AXON_BOT_APP_ID }}
          private_key: ${{ secrets.AXON_BOT_PRIVATE_KEY }}
      - name: Invoke somking test with inputs
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Somking test suit
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "axon_linux_release_tag": "${{ needs.version.outputs.tag }}" }'

  trigger-build-docker-image:
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
      - uses: actions/checkout@v3
      - name: Generate axon-bot token
        id: generate_axon_bot_token
        uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.AXON_BOT_APP_ID }}
          private_key: ${{ secrets.AXON_BOT_PRIVATE_KEY }}
      - name: Invoke build docker image with inputs
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Build docker image
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "dispatch": "${{ needs.version.outputs.tag }}" }'
