name: Total Size
on:
  pull_request:

jobs:
  Size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
